In [46]:
import numpy as np
a = np.array([
                [1, 2, 3, 3, 1],
                [6, 8, 11, 10, 7]
             ])

print("Исходный массив :")
print(a)

mean_a = a.mean(axis=1)
print("Усредненный массив :")
print(mean_a)

Исходный массив :
[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
Усредненный массив :
[2.  8.4]


In [76]:
np.shape(a)
np.shape(mean_a)
a_centered = np.array(a.T - mean_a)
print("Центрированный массив:")
print(a_centered)

Центрированный массив:
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [96]:
print(np.shape(a_centered))

a1 = np.array(a_centered[0:, 0:1])
print(a1)

a2 = np.array(a_centered[0:, 1:2])
print(a2)

a_centered_sp = np.dot(a1.flatten(), a2.flatten())
print("скалярное произведение столбцов:")
print(a_centered_sp)

(5, 2)
[[-1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [-1.]]
[[-2.4]
 [-0.4]
 [ 2.6]
 [ 1.6]
 [-1.4]]
скалярное произведение столбцов:
8.0
